- hosts: 127.0.0.1
  connection: local
  vars_files:
    - vars/main.yml
  tasks:
    - name: create container
      docker:
        name: tmp-oracle-wls-domain
        image: "{{ base_image }}"
        command: sleep infinity
        state: started

    - add_host:
        name: tmp-oracle-wls-domain
        groups: docker
        ansible_connection: docker

- hosts: tmp-oracle-wls-domain
  connection: docker
  tasks:
    - file:
        path: /tmp
        state: directory
        mode: 0777

    - copy:
        src: domain.py
        dest: /opt/oraclefmw/domain.py
      become: yes
      become_user: oraclefmw

    - shell: "/opt/oraclefmw/product/oracle_home/oracle_common/common/bin/wlst.sh /opt/oraclefmw/domain.py"
      register: domain
      ignore_errors: yes
      become: yes
      become_user: oraclefmw

    - debug:
        var: domain

- hosts: 127.0.0.1
  connection: local
  vars_files:
    - vars/main.yml
  tasks:
    - name: docker commit
      command: "docker commit tmp-oracle-wls-domain tmp-oracle-wls-domain"

    - name: docker kill
      command: "docker kill tmp-oracle-wls-domain"

    - name: docker rm
      command: "docker rm tmp-oracle-wls-domain"

    - name: build image
      command: "docker build -t {{ image_name }} docker"

    - name: docker tag
      command: "docker tag {{ image_name }} {{ image_name }}:{{ item }}"
      with_items: "{{ tags }}"

    - name: docker rmi
      command: "docker rmi tmp-oracle-wls-domain"

    # @todo wait for private repository
    - name: docker push
      command: "docker push {{ image_name }}:{{ item }}"
      with_items: "{{ tags }}"
